/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminRecipesRouteImport } from './routes/admin/recipes'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSalesEntryRouteImport } from './routes/admin/sales-entry'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/admin/recipes',
  path: '/admin/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesEntryRoute = AdminSalesEntryRouteImport.update({
  id: '/admin/sales-entry',
  path: '/admin/sales-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-entry': typeof AdminSalesEntryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-entry': typeof AdminSalesEntryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-entry': typeof AdminSalesEntryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/menu'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/sales-entry'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/menu'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/sales-entry'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/menu'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/sales-entry'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  MenuRoute: typeof MenuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesEntryRoute: typeof AdminSalesEntryRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/admin/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales-entry': {
      id: '/admin/sales-entry'
      path: '/admin/sales-entry'
      fullPath: '/admin/sales-entry'
      preLoaderRoute: typeof AdminSalesEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  MenuRoute: MenuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRecipesRoute: AdminRecipesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesEntryRoute: AdminSalesEntryRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
